[package]
name = "slz"
description = "Streaming LZMA compression"
homepage = "https://github.com/hasenbanck/slz/"
repository = "https://github.com/hasenbanck/slz/"
documentation = "https://https://docs.rs/lzma/latest/slz/"
license = "Apache-2.0"
version = "0.1.0"
keywords = ["lzma", "slz"]
edition = "2024"
rust-version = "1.89"

[[bin]]
name = "slz"
path = "src/bin/slz.rs"

[dependencies]
lzma-rust2 = { version = "0.8", default-features = false, features = ["std", "optimization", "encoder"] }
blake3 = { version = "1.8", default-features = false, features = ["std", "no_avx512"] }

[dev-dependencies]
hex-literal = "1"
hexdump = "0.1"

[features]
default = ["std"]
std = []
