[workspace]
members = ["libslz"]
resolver = "2"

[workspace.dependencies]
clap = { version = "4", default-features = false, features = ["std", "help"] }
blake3 = { version = "1" }
hex-literal = "1"

[package]
name = "slz"
description = "Streaming LZMA compression command-line tool"
homepage = "https://github.com/hasenbanck/slz/"
repository = "https://github.com/hasenbanck/slz/"
license = "Apache-2.0"
version = "0.1.0"
keywords = ["lzma", "slz", "compression"]
edition = "2024"
rust-version = "1.89"
exclude = ["tests/data/"]

[[bin]]
name = "slz"
path = "src/main.rs"

[dependencies]
libslz = { version = "0.1", features = ["std"], path = "libslz" }
clap = { workspace = true }

# Activate this block section if you want to run benchmark.
# criterion = { version = "0.7", features = ["html_reports"] }
#
#[dev-dependencies]
#criterion = { workspace = true }
#
#[[bench]]
#name = "comparison"
#harness = false
